version: "3.7"
services:
  submission-runner:
    build: ./
    image: aiwarsoc/submission-runner:debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: "./runner"
        target: "/exec/runner"
        read_only: true
      - type: bind
        source: "./sandbox"
        target: "/exec/sandbox"
        read_only: true
      - type: bind
        source: "./shared"
        target: "/exec/shared"
        read_only: true
    ports:
      - "5000:5000"
    environment:
      SANDBOX_PYTHON_TIMEOUT: 10s
      SANDBOX_CONTAINER_TIMEOUT: 12
      SANDBOX_API_DEBUG: "True"
      SANDBOX_MEM_LIMIT: 256m
      SANDBOX_NANO_CPUS: 1000