version: "3.7"
services:
  submission-runner-docker:
    image: docker:dind
    privileged: true
    volumes:
      - "submission-runner-docker-certs:/certs/client"
      - "submission-runner-dind-data:/var/lib/docker"
    networks:
      submission-runner:
        aliases:
          - docker
    environment:
      - "DOCKER_TLS_CERTDIR=/certs"
    restart: unless-stopped
    init: true
  submission-runner:
    build: ./
    image: aiwarssoc/submission-runner:debug
    volumes:
      - "./runner:/home/subrunner/runner"
      - "./sandbox:/home/subrunner/sandbox"
      - "./shared:/home/subrunner/shared"
      - "./tmp/repositories:/home/subrunner/repositories:ro"
      - "submission-runner-docker-certs:/certs/client:ro"
      - "./debug_config.yml:/home/subrunner/config.yml:ro"
    networks:
      - database
      - submission-runner
    ports:
      - "5000:8080"
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - database
      - submission-runner-docker
    init: true
  web-server:
    build: ../front-end
    image: aiwarssoc/front-end:debug
    ports:
      - "80:8080"
    volumes:
      - "../front-end/server:/home/web_user/server"
      - "./tmp/repositories:/home/web_user/repositories"
      - "./debug_config.yml:/home/web_user/config.yml:ro"
    networks:
      - redis
      - database
    secrets:
      - secret_key
    depends_on:
      - database
      - redis
  redis:
    image: redis
    volumes:
      - "./tmp/redis:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
  database:
    image: postgres
    networks:
      database:
        aliases:
          - database
    environment:
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database
    depends_on:
      - database

networks:
  redis:
  database:
  submission-runner:
secrets:
  secret_key:
    file: ./debug_secret.txt
volumes:
  submission-runner-docker-certs:
  submission-runner-dind-data:
