version: "3.7"
services:
  submission-runner:
    build: ./
    image: aiwarsoc/submission-runner:debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: "./runner"
        target: "/exec/runner"
        read_only: true
      - type: bind
        source: "./sandbox"
        target: "/exec/sandbox"
        read_only: true
      - type: bind
        source: "./shared"
        target: "/exec/shared"
        read_only: true
      - "./tmp/runner:/tmp/sandbox"
    ports:
      - "5000:5000"
    networks:
      - database
    environment:
      DEBUG: "True"
      SANDBOX_COMMAND_TIMEOUT: 15s
      SANDBOX_CONTAINER_TIMEOUT: 15s
      SANDBOX_PARSER_TIMEOUT: 10
      SANDBOX_MEM_LIMIT: 256m
      SANDBOX_CPU_COUNT: 0.5
  database:
    image: aiwarssoc/database
    volumes:
      - "./debug/database:/database"
    networks:
      database:
        aliases:
          - database
    environment:
      DEBUG: "True"
      INITIAL_SCORE: 1000
      SCORE_TURBULENCE_MILLIS: 5000
      HEALTH_BUFFER: 100
networks:
  database: