version: "3.7"
services:
  submission-runner-docker:
    image: docker:dind
    privileged: true
    expose:
      - "2376"
    volumes:
      - "submission-runner-docker-certs:/certs/client"
      - "submission-runner-dind-data:/var/lib/docker"
    networks:
      submission-runner:
        aliases:
          - docker
    environment:
      - "DOCKER_TLS_CERTDIR=/certs"
    restart: unless-stopped
    init: true
  submission-runner:
    build: ./
    image: aiwarssoc/submission-runner:debug
    volumes:
      - type: bind
        source: "./runner"
        target: "/home/subrunner/runner"
        read_only: true
      - type: bind
        source: "./sandbox"
        target: "/home/subrunner/sandbox"
        read_only: true
      - type: bind
        source: "./shared"
        target: "/home/subrunner/shared"
        read_only: true
      - "./tmp/repositories:/repositories"
      - "submission-runner-docker-certs:/certs/client:ro"
    networks:
      - database
      - submission-runner
    ports:
      - "5000:8080"
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
      DEBUG: "True"
      SANDBOX_COMMAND_TIMEOUT: 25s
      SANDBOX_CONTAINER_TIMEOUT: 25s
      SANDBOX_PARSER_TIMEOUT: 20
      SANDBOX_MEM_LIMIT: 256m
      SANDBOX_CPU_COUNT: 0.5
      DATABASE_CONNECTION: "postgresql://debug:debug@database"
      SCORE_TURBULENCE_MILLIS: 2000
      INITIAL_SCORE: 1000
      GAMEMODE: chess
      MATCHMAKERS: 1
      GAME_OPTIONS: '{"chess960": true}'
      SECONDS_PER_RUN: 20
    depends_on:
      - database
      - submission-runner-docker
    init: true
  web-server:
    build: ../front-end
    image: aiwarssoc/front-end:debug
    ports:
      - "80:8080"
    volumes:
      - "../front-end/server:/home/web_user/server"
      - "./tmp/repositories:/repositories"
    networks:
      - redis
      - database
    environment:
      DEBUG: "True"
      SERVER_NAME: "lvh.me"
      CLIENT_ID: "389788965612-qh4j3n7fh14nfjbg7u1tmlb59mudmobj.apps.googleusercontent.com"
      DATABASE_CONNECTION: "postgresql://debug:debug@database"
      MAX_REPO_SIZE_BYTES: 10000000
      INITIAL_SCORE: 1000
    secrets:
      - secret_key
    depends_on:
      - database
      - redis
  redis:
    image: redis
    volumes:
      - "./tmp/redis:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
  database:
    image: postgres
    networks:
      database:
        aliases:
          - database
    environment:
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database
    depends_on:
      - database

networks:
  redis:
  database:
  submission-runner:
secrets:
  secret_key:
    file: ./debug_secret.txt
volumes:
  submission-runner-docker-certs:
  submission-runner-dind-data:
