version: "3.7"
services:
  submission-runner:
    build: ./
    image: aiwarsoc/submission-runner:debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: "./runner"
        target: "/exec/runner"
        read_only: true
      - type: bind
        source: "./sandbox"
        target: "/exec/sandbox"
        read_only: true
      - type: bind
        source: "./shared"
        target: "/exec/shared"
        read_only: true
      - "./tmp/runner:/tmp/sandbox"
      - "./tmp/repositories:/repositories"
      - "./tmp/database:/database"
    ports:
      - "5000:5000"
    environment:
      DEBUG: "True"
      SANDBOX_COMMAND_TIMEOUT: 15s
      SANDBOX_CONTAINER_TIMEOUT: 15s
      SANDBOX_PARSER_TIMEOUT: 10
      SANDBOX_MEM_LIMIT: 256m
      SANDBOX_CPU_COUNT: 0.5
      DATABASE_CONNECTION: "sqlite+pysqlite:////database/database.sqlite"
  web-server:
    build: ../front-end
    image: aiwarssoc/front-end:debug
    ports:
      - "80:8080"
    volumes:
      - "../front-end/server:/home/web_user/server"
      - "./tmp/repositories:/repositories"
      - "./tmp/database:/database"
    networks:
      - redis
    environment:
      DEBUG: "True"
      TESTING: "True"
      SERVER_NAME: "lvh.me"
      CLIENT_ID: "389788965612-qh4j3n7fh14nfjbg7u1tmlb59mudmobj.apps.googleusercontent.com"
      DATABASE_CONNECTION: "sqlite+pysqlite:////database/database.sqlite"
      INITIAL_SCORE: 1000
      SCORE_TURBULENCE_MILLIS: 5000
      HEALTH_BUFFER: 100
      MAX_REPO_SIZE_BYTES: 10000000
    secrets:
      - secret_key
  redis:
    image: redis
    volumes:
      - "./tmp/redis:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
networks:
  redis:
secrets:
  secret_key:
    file: ./debug_secret.txt