db_connection: "postgresql://debug:debug@database"
debug: false
profile: false
soc_name: "cuwais"
google_client_id: "389788965612-3hlb0b2lqamt2v7jupphcggnk0t9sol9.apps.googleusercontent.com"
allowed_email_domain: ~
front_end:
  server_name: "lvh.me"
submission_runner:
  matchmakers: 2
