version: "3.7"
services:
  submission-runner:
    build: ./
    image: aiwarsoc/submission-runner:debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "scripts:/sandbox-scripts"
      - "./runner:/runner"
      - "./shared:/runner/shared"
    ports:
      - "5000:5000"
    environment:
      SANDBOX_PYTHON_TIMEOUT: 10s
      SANDBOX_CONTAINER_TIMEOUT: 12
      SANDBOX_API_DEBUG: "True"
      SANDBOX_MEM_LIMIT: 256m
      SANDBOX_NANO_CPUS: 1000
      SANDBOX_SCRIPTS_VOLUME: "scripts"

volumes:
  scripts:
    name: scripts