db_connection: "postgresql://debug:debug@database"
debug: false
profile: false
submission_runner:
  sandbox_unrun_timeout_seconds: 360
  sandbox_run_timeout_seconds: 360
  sandbox_memory_limit: 256m
  sandbox_cpu_count: 0.5
