db_connection: "postgresql://debug:debug@database"
debug: false
profile: false
initial_score: 1000
score_turbulence: 0.5
submission_runner:
  target_seconds_per_game: 10
  sandbox_unrun_timeout_seconds: 360
  sandbox_run_timeout_seconds: 360
  sandbox_memory_limit: 256m
  sandbox_cpu_count: 0.5
  matchmakers: 6
gamemode:
  id: chess
  options:
    turn_time: 10
    player_turn_time: 300
    chess960: true
localisation:
